# Site settings
title: Chirality
email: booking@chirality.band
description: "Chirality."
baseurl: "https://chirality.band"
url: "https://chirality.band"

instagram_username: ragav.music

# Build settings
markdown: kramdown
