# Site settings
title: Ragav Venkatesan
email: booking@ragav.net
description: "Welcome to the webpage of Ragav Venkatesan."
baseurl: "https://ragav.net/epk"
url: "https://ragav.net/epk"

instagram_username: ragav.music

# Build settings
markdown: kramdown
